version: '3.8'

services:
    odoo:
        build: .
        container_name: odoo-app
        ports:
            - '8069:8069'
        volumes:
            - ./addons:/mnt/addons
            - ./custom_addons:/mnt/custom_addons
            - ./odoo.conf:/etc/odoo/odoo.conf
            - ./data:/var/lib/odoo
        environment:
            - HOST=aws-0-eu-central-1.pooler.supabase.com
            - USER=${DB_USER}
            - PASSWORD=${DB_PASSWORD}
            - PGHOST=${DB_HOST}
            - PGUSER=${DB_USER}
            - PGPASSWORD=${DB_PASSWORD}
            - PGPORT=${DB_PORT}
            - PGSSLMODE=${DB_SSLMODE}
            - ADMIN_PASSWD=${ADMIN_PASSWD}
            - ADDONS_PATH=/mnt/addons,/mnt/custom_addons
        command: [
            "odoo",
            "--db_host=${DB_HOST}",
            "--db_user=${DB_USER}",
            "--db_password=${DB_PASSWORD}",
            "--db_port=${DB_PORT}",
            "--db_sslmode=${DB_SSLMODE}",
            "--admin_passwd=${ADMIN_PASSWD}",
            "--addons-path=/mnt/addons,/mnt/custom_addons"
        ]
        command: ['odoo', '--config=/etc/odoo/odoo.conf']
        restart: always
