version: '3.8'

services:
    odoo:
        image: odoo:18
        container_name: odoo-app
        ports:
            - '8069:8069'
        volumes:
            - ./addons:/mnt/addons
            - ./custom_addons:/mnt/custom_addons
            - ./odoo.conf:/etc/odoo/odoo.conf
            - ./data:/var/lib/odoo
        environment:
            - HOST=127.0.0.1
            - USER=odoo
            - PASSWORD=admin123
        command: ['odoo', '--config=/etc/odoo/odoo-locale.conf']
